console.log("Nishant Maheshwari")
console.log("Hello World")
console.log("This is my first JavaScript code")
console.log("I am learning JavaScript in DevContainer")
console.log("This is my first JavaScript code in DevContainer")
console.log("I am excited to learn more about JavaScript")
console.log("I am looking forward to mastering JavaScript")
console.log("I am enjoying the process of learning JavaScript")
console.log("I am grateful for the opportunity to learn JavaScript")